FROM reg.docker.alibaba-inc.com/ajdk/8.alios5
RUN mkdir -p /home/admin/kube-controller-manager/log && \
    mkdir -p /home/admin/log && \
    yum install -y -b current t-staragent-agent2 && \
    yum install -y ali-sls-ilogtail
ENTRYPOINT ["/sbin/init"]
VOLUME ["/home/admin/kube-controller-manager/log","/home/admin/log/","/home/staragent/plugins"]
COPY environment/alibaba/kube-controller-manager/bin/logrotate /etc/cron.daily/
COPY environment/alibaba/kube-controller-manager/cfg/logrotate.conf /etc/logrotate.d/controller
COPY environment/alibaba/kube-controller-manager/bin/rc.local /etc/rc.local
COPY environment/alibaba/kube-controller-manager/bin/start-k8s-controller.sh /home/admin/kube-controller-manager/bin/
COPY environment/alibaba/kube-controller-manager/bin/kube-controller-manager /home/admin/kube-controller-manager/bin/
WORKDIR /home/admin/kube-controller-manager
