// Automatically generated by MockGen. DO NOT EDIT!
// Source: $GOPATH/src/k8s.io/kubernetes/pkg/kubelet/autonomy/sketch/builders/sketch_builder.go

package testing

import (
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v1alpha1 "k8s.io/kubernetes/pkg/kubelet/autonomy/sketch/api/v1alpha1"
	core "k8s.io/kubernetes/pkg/kubelet/autonomy/sketch/core"
)

// Mock of StatsProvider interface
type MockStatsProvider struct {
	ctrl     *gomock.Controller
	recorder *_MockStatsProviderRecorder
}

// Recorder for MockStatsProvider (not exported)
type _MockStatsProviderRecorder struct {
	mock *MockStatsProvider
}

func NewMockStatsProvider(ctrl *gomock.Controller) *MockStatsProvider {
	mock := &MockStatsProvider{ctrl: ctrl}
	mock.recorder = &_MockStatsProviderRecorder{mock}
	return mock
}

func (_m *MockStatsProvider) EXPECT() *_MockStatsProviderRecorder {
	return _m.recorder
}

func (_m *MockStatsProvider) GetPodByName(namespace string, name string) (*v1.Pod, bool) {
	ret := _m.ctrl.Call(_m, "GetPodByName", namespace, name)
	ret0, _ := ret[0].(*v1.Pod)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

func (_mr *_MockStatsProviderRecorder) GetPodByName(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetPodByName", arg0, arg1)
}

func (_m *MockStatsProvider) GetNode() (*v1.Node, error) {
	ret := _m.ctrl.Call(_m, "GetNode")
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStatsProviderRecorder) GetNode() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetNode")
}

// Mock of SketchBuilder interface
type MockSketchBuilder struct {
	ctrl     *gomock.Controller
	recorder *_MockSketchBuilderRecorder
}

// Recorder for MockSketchBuilder (not exported)
type _MockSketchBuilderRecorder struct {
	mock *MockSketchBuilder
}

func NewMockSketchBuilder(ctrl *gomock.Controller) *MockSketchBuilder {
	mock := &MockSketchBuilder{ctrl: ctrl}
	mock.recorder = &_MockSketchBuilderRecorder{mock}
	return mock
}

func (_m *MockSketchBuilder) EXPECT() *_MockSketchBuilderRecorder {
	return _m.recorder
}

func (_m *MockSketchBuilder) Build(batch *core.DataBatch) *v1alpha1.SketchSummary {
	ret := _m.ctrl.Call(_m, "Build", batch)
	ret0, _ := ret[0].(*v1alpha1.SketchSummary)
	return ret0
}

func (_mr *_MockSketchBuilderRecorder) Build(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Build", arg0)
}
