apiVersion: audit.k8s.io/v1beta1  #this is required in Kubernetes 1.8
kind: Policy
rules:
  # Don't log watch requests
  - level: None
    verbs: ["watch", "get"]

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
    - "/api*" # Wildcard matching.
    - "/version"

  # Log the request body of configmap changes in kube-system.
  - level: Request
    resources:
    - group: "" # core API group
      resources: ["configmaps"]
    # This rule only applies to resources in the "kube-system" namespace.
    # The empty string "" can be used to select non-namespaced resources.
    namespaces: ["kube-system"]

  # Log configmap and secret changes in all other namespaces at the Metadata
  # level.
  - level: Metadata
    resources:
    - group: "" # core API group
      resources: ["secrets", "configmaps"]

  # Log all other resources in core and extensions at the Request level.
  - level: Request
    verbs: ["create", "delete", "patch", "update"]
    resources:
    - group: "" # core API group
    - group: "extensions" # Version of group should NOT be included.
    - group: "basic.sigma" # core API group
    - group: "extensions.sigma" # Version of group should NOT be included.

  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata