// +build multitenancy

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"fmt"
	"runtime/debug"

	"gitlab.alipay-inc.com/antcloud-aks/aks-k8s-api/pkg/multitenancy"
	multitenancycache "gitlab.alipay-inc.com/antcloud-aks/aks-k8s-api/pkg/multitenancy/cache"
	multitenancyutil "gitlab.alipay-inc.com/antcloud-aks/aks-k8s-api/pkg/multitenancy/util"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1"
)

// FischerLister helps list Fischers.
type FischerLister interface {
	// List lists all Fischers in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.Fischer, err error)
	// Get retrieves the Fischer from the index for a given name.
	Get(name string) (*v1alpha1.Fischer, error)
	FischerListerExpansion
}

type fischerLister struct {
	indexer cache.Indexer
	tenant  multitenancy.TenantInfo
}

func (s *fischerLister) ShallowCopyWithTenant(tenant multitenancy.TenantInfo) interface{} {
	return &fischerLister{
		indexer: s.indexer,
		tenant:  tenant,
	}
}

// NewFischerLister returns a new FischerLister.
func NewFischerLister(indexer cache.Indexer) FischerLister {
	return &fischerLister{indexer: indexer}
}

// List lists all Fischers in the indexer.
func (s *fischerLister) List(selector labels.Selector) (ret []*v1alpha1.Fischer, err error) {
	if s.tenant != nil {
		err = multitenancycache.ListAllWithTenant(s.indexer, selector, s.tenant, func(m interface{}) {
			ret = append(ret, m.(*v1alpha1.Fischer))
		})
	} else {
		err = cache.ListAll(s.indexer, selector, func(m interface{}) {
			ret = append(ret, m.(*v1alpha1.Fischer))
		})
	}
	return ret, err
}

// Get retrieves the Fischer from the index for a given name.
func (s *fischerLister) Get(name string) (*v1alpha1.Fischer, error) {
	if s.tenant == nil {
		// fail hard so that we don't allow any cluster-scoped get w/o tenant
		debug.PrintStack()
		return nil, fmt.Errorf("cannot get fischer w/o specifying tenant")
	}

	obj, exists, err := s.indexer.GetByKey(multitenancyutil.TransformTenantInfoToJointString(s.tenant, "/") + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("fischer"), name)
	}
	return obj.(*v1alpha1.Fischer), nil
}
