// Code generated by mockery v1.0.0. DO NOT EDIT.

package testing

import mock "github.com/stretchr/testify/mock"
import sketch "k8s.io/kubernetes/pkg/kubelet/autonomy/sketch"

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// GetSketch provides a mock function with given fields:
func (_m *Provider) GetSketch() sketch.Snapshoter {
	ret := _m.Called()

	var r0 sketch.Snapshoter
	if rf, ok := ret.Get(0).(func() sketch.Snapshoter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sketch.Snapshoter)
		}
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *Provider) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Provider) Stop() {
	_m.Called()
}
